# config/services.yaml
# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    dive_photos_directory: '%kernel.project_dir%/public/images'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # maakt alle classes in src/ beschikbaar als services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Specifieke config voor je upload-service
    App\Service\PhotoUploadService:
        arguments:
            $uploadDir: '%dive_photos_directory%'
